dirs:
    cfg_dir : ".."

model:

glass:
# Windows size [m2]
    E  : 9.5
    SE : 0
    S  : 0
    SW : 0
    W  : 9.5
    NW : 0
    N  : 0
    NE : 0
    g_value : 0.7

timing:
    days_sim : 365
    interval : NEN5060
    unit : ss

thermal:
    #Thermal resistance per unit area (thermal insulation), 
    #R-value [m2K/W] (Rc_facade)
    Rc_facade : 1.3
    #Window thermal transmittance, U-value [W/m2K]
    U_glass : 2.9
    #Specific heat capacity construction [J/kgK]
    c_facade: [840, 840, 840]
    c_internal_mass: [840, 840, 840]

dimensions:
    #Envelope surface (facade + roof + ground) [m2] (A_facade)
    A_facade : 160.2
    #Floor and internal walls surface [m2]
    A_internal_mass: 170 # 106 + 64
    #Internal volume [m3]
    V_dwelling : 275.6

ventilation:
    #Ventilation, air changes per hour [#/h]
    n : 0.55
    #convection factor (solar radiation): 
    #the convection factor is the part of the solar radiation 
    #that enters the room and is released directly convectively into the room
    CF : 0.8

construction:
    #Facade and internal mass (floor, internal walls) construction
    # Light_weight : 0 / Middle_weight : 1  / Heavy_weight : 2
    N_facade  : 1
    N_internal_mass : 1
    #Construction thickness [m]
    th_facade: [ 0.1,  0.1, 0.2 ]
    th_internal_mass: [0.1, 0.1, 0.2]
    #Density construction in [kg/m3]
    rho_facade: [500, 1000, 2500]
    rho_internal_mass: [500, 1000, 2500]

initial:
    # density air in [kg/m3]
    rho_air : 1.20
    # specific heat capacity air [J/kgK]
    c_air  : 1005
    # Heat transfer coefficient [W/m2K]. 
    # Interior surface thermal resistance Ri= 1/ alpha_i_facade
    alpha_i_facade : 8
    # Heat transfer coefficient [W/m2K]. 
    # Exterior surface thermal resistance Rse = 1/ alpha_e_facade
    alpha_e_facade : 23
    # Heattransfer coefficient [W/m2K].
    # Internal wall thermal resistance
    alpha_internal_mass : 8

internal:
    # Internal heat difference between day and night [W]
    delta_Q : 150
    # Daytime internal heat generation [W]
    Q_day : 400
    # Presence from [hour]
    t1 : 8
    # Presence until [hour]
    t2 : 23

setpoint:
    # Presence from [hour]
    t1 : 8
    # Presence until [hour]
    t2 : 23
    # Set temperature of thermostat at night from time t2
    Night_T_SP : 17
    # Set wishes temperature of thermostat
    Day_T_SP   : 20
    # Set the temperature when people are not at home
    Flex_T_SP_dayoff   : 18
    Flex_T_SP_workday  : 17
    # Define Wake up time    
    # Define wake up time in the morning, temperature set to 20
    Wu_time : 7
    # Go to work time/ leave the house
    # Define time that people go to work.
    Work_time : 8
    # Define time that people go out for shopping.
    shopping_time : 13
    # Back to home
    #Define time that people back from work 18:00
    back_home_from_work : 18
    #Define time that people back from work 18:00
    back_home : 15

controller:
    # propotional gain
    kp : 7000
    # intergal
    ki : 0
    # derivative
    kd : 0
   

   

radiator:
    # Heat transfer coefficient of the radiator
    Urad : 30
    # Area of the radiator
    Arad : 10
    # Cp value of water
    cpwater : 4180
    #Volume of the radiator
    volume_rad : 0.050
    #density of the water
    rhowater : 1000
    #Volume of the buffervessel
    volume_buffervessel : 0.150
    #Waterflow through the radiator
    mdot : 0.150     
     
    


