dirs:
    cfg_dir : ".."

model:

glass_z1:
    E : 0
    SE : 0
    S : 4.75
    SW : 0
    W : 0
    NW : 0
    N : 4.75
    NE : 0
    g_value : 0.7
    
glass_z2:
    E : 0
    SE : 0
    S : 4.75
    SW : 0
    W : 0
    NW : 0
    N : 4.75
    NE : 0
    g_value : 0.7

timing:
    days_sim : 20
    interval : NEN5060
    unit : ss

thermal:
    #Envelope thermal resistance, R-value [m2/KW] (Rc_facade)
    Rc_facade : 1.3
    #Window thermal transmittance, U-value [W/m2K]
    U_glass : 2.9
    #Specific heat capacity construction [J/kgK]
    c_facade: [840, 840, 840]
    c_internal_mass: [840, 840, 840]

dimensions:
    #Envelope surface (facade + roof + ground) [m2] (A_facade)
    A_facade_z1 : 160.2
    A_facade_z2 : 160.2
    #Floor and internal walls surface [m2]
    A_internal_mass_z1: 59.5           #(106+64)/2 - A_cc/2 
    A_internal_mass_z2: 59.5
    # Area of middle CC layer [m2]
    A_cc: 51
    #Internal volume [m3]
    V_dwelling_z1 : 137.8
    V_dwelling_z2 : 137.8

ventilation:
    #Ventilation, air changes per hour [#/h]
    n : 0.55
    #?????????????
    CF : 0.8

construction:
    #Facade and internal mass (floor, internal walls) construction
    # Light_weight : 0 / Middle_weight : 1  / Heavy_weight : 2
    N_facade  : 2
    N_internal_mass : 2
    #Construction thickness [m]
    th_facade: [ 0.1,  0.1, 0.2 ]
    th_internal_mass: [0.1, 0.1, 0.2]
    #Density construction in [kg/m3]
    rho_facade: [500, 1000, 2500]
    rho_internal_mass: [500, 1000, 2500]

initial:
    # density air in [kg/m3]
    rho_air : 1.20
    # specific heat capacity air [J/kgK]
    c_air  : 1005
    # to be defined, interior surface thermal resistance 
    #Ri =1/alpha_i_facade = 0.125 (Rc-Waarde=0.13,ISO 6946)
    alpha_i_facade : 8
    # to be defined,  # exterior surface thermal resistance 
    #RSe =1/alpha_e_facade (0,04 m²K/W	ISO 6946	Most external surfaces 
                             #e.g. external side of exterior wall)
    alpha_e_facade : 23
    # to be defined
    alpha_internal_mass : 8

internal:
    # Internal heat difference between day and night [W]
    delta_Q : 150
    # Daytime internal heat generation [W]
    Q_day : 400
    # Presence from [hour]
    t1 : 8
    # Presence until [hour]
    t2 : 23

setpoint:
    # Presence from [hour]
    t1 : 8
    # Presence until [hour]
    t2 : 23
    # Set temperature of thermostat at night from time t2
    Night_T_SP : 17
    # Set wishes temperature of thermostat
    Day_T_SP : 20
    # Define Wake up time
    # Define wake up time in the morning, temperature set to 20
    Wu_time : 7
    # Go to work time/ leave the house
    # Define time that people go to work.
    Work_time : 8
    # Define time that people go out for shopping.
    shopping_time : 13
    # Back to home
    #Define time that people back from work 18:00
    back_home_from_work : 18
    #Define time that people back from work 18:00
    back_home : 15

controller:
    # propotional gain
    kp : 7000
    # intergal
    ki : 0
    # derivative
    kd : 0
   

   


