name: ff311
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.11
  - pytorch::pytorch
  - scikit-learn-intelex
  - pvlib
  - matplotlib
  - scipy
  - pandas
  - openpyxl
  - pyyaml
  - ruamel.yaml
  - holidays
  - pytest
  - colored-traceback
  - networkx
  - requests
  - tqdm
  - simple-pid
  - jupyter
  - sphinx
  - build
  - twine
  - myst-parser
  - pip
  - coolprop
  - pip:
    - solarenergy
    - sphinx-rtd-theme
